import type { Metadata } from "next";
import "./globals.css";
import { paragraphFont, titleFont } from "./fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface childrenProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<childrenProps> = ({ children }: childrenProps) => {
  return (
    <html lang="en">
      <body className="bg-prime-100">
        <main className={`${titleFont.variable} ${paragraphFont.variable}`}>
            {/* <Navbar /> */}
            {children}
            {/* <Footer /> */}
        </main>
      </body>
    </html>
  );
};

export default RootLayout;
